# Validate explicit native command metadata and emit the packaged manifest.
#
# Usage: tclsh tools/genmanifest.tcl <srcdir> <out.tcl>
#
# This file deliberately derives only the registration set.  Domains, errors,
# options, subcommands, and return shapes are behavioral contracts and live in
# manifest_spec.tcl; guessing them from C helper regions produced plausible but
# false metadata whenever an implementation moved.

if {[llength $argv] != 2} {
    puts stderr "usage: genmanifest.tcl <srcdir> <out.tcl>"
    exit 2
}
lassign $argv SRC OUT

set HERE [file dirname [file normalize [info script]]]
source [file join $HERE manifest_spec.tcl]
set manifest $::machteld::manifest::native
set private $::machteld::manifest::private

proc slurp {path} {
    set channel [open $path r]
    fconfigure $channel -translation lf
    set text [read $channel]
    close $channel
    return $text
}

set registered {}
foreach path [lsort [glob -directory $SRC *.c]] {
    set text [slurp $path]
    foreach {_ command} [regexp -all -inline \
            {Tcl_CreateObjCommand\s*\(\s*interp\s*,\s*"::machteld::([A-Za-z][A-Za-z0-9_]*)"} \
            $text] {
        if {$command in $registered} {
            error "genmanifest: ::machteld::$command is registered more than once"
        }
        lappend registered $command
    }
}
set registered [lsort $registered]
set public [lsort [dict keys $manifest]]
set expected [lsort [concat $public $private]]
if {$registered ne $expected} {
    set missing {}
    set extra {}
    foreach command $registered {
        if {$command ni $expected} { lappend missing $command }
    }
    foreach command $expected {
        if {$command ni $registered} { lappend extra $command }
    }
    error "genmanifest: registration/spec mismatch; unlisted registrations={$missing}; absent registrations={$extra}"
}

dict for {verb entry} $manifest {
    foreach required {kind domain codes options} {
        if {![dict exists $entry $required]} {
            error "manifest_spec: $verb has no $required field"
        }
    }
    if {[dict get $entry kind] ne "c"} {
        error "manifest_spec: native verb $verb must have kind c"
    }
    set domain [dict get $entry domain]
    if {![regexp {^[A-Z][A-Z0-9_]*$} $domain]} {
        error "manifest_spec: $verb has invalid domain {$domain}"
    }
    set options [dict get $entry options]
    if {[llength $options] != [llength [lsort -unique $options]]} {
        error "manifest_spec: $verb repeats an option"
    }
    foreach option $options {
        if {![regexp {^-[a-z][a-z0-9]*$} $option]} {
            error "manifest_spec: $verb has invalid option {$option}"
        }
    }
    if {[dict exists $entry subcommands]} {
        dict for {subcommand subentry} [dict get $entry subcommands] {
            if {![dict exists $subentry options]} {
                error "manifest_spec: $verb $subcommand has no options field"
            }
            foreach option [dict get $subentry options] {
                if {$option ni $options} {
                    error "manifest_spec: $verb $subcommand option $option is absent from the verb union"
                }
            }
        }
    }
}

file mkdir [file dirname $OUT]
set channel [open $OUT w]
fconfigure $channel -translation lf
puts $channel "# GENERATED by tools/genmanifest.tcl from tools/manifest_spec.tcl -- do not edit."
puts $channel "# Native registrations were validated against src/*.c at build time."
puts $channel "set ::machteld::MANIFEST \{"
foreach verb [lsort [dict keys $manifest]] {
    puts $channel "    [list $verb] [list [dict get $manifest $verb]]"
}
puts $channel "\}"
close $channel

puts "genmanifest: validated [llength $registered] registrations; emitted [dict size $manifest] public native verbs"
